import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  AirplaneTilt, ArrowLeft, ArrowRight, Bell, Buildings, CalendarBlank, CaretRight,
  ChartDonut, Check, CheckCircle, Clock, Coins, Copy, ForkKnife, Gavel, Hourglass, Info,
  Link, LockKey, MagicWand, MapPin, Pause, Play, Plus, Receipt, ShareNetwork,
  ShieldCheck, Sparkle, SpinnerGap, SuitcaseRolling, Ticket, TrendDown, TrendUp, UsersThree,
  Warning, X,
} from '@phosphor-icons/react'
import {
  budget, destinationPacks, itineraryDays, meetingRounds, osakaPreferences, preferenceSliders,
  replayMessages, reservations, roomMembers, type DestinationPack,
} from './v11Data'

type Stage = 'landing' | 'destinations' | 'create' | 'invite' | 'lobby' | 'hard' | 'sliders' | 'cards' | 'free' | 'persona-loading' | 'persona' | 'submitted' | 'running' | 'complete' | 'result' | 'replay'
type ResultTab = 'summary' | 'itinerary' | 'booking' | 'fairness' | 'backup'

const demoStages: Stage[] = ['landing','destinations','create','invite','lobby','hard','sliders','cards','free','persona-loading','persona','submitted','running','complete','result','replay']
const resultTabs: ResultTab[] = ['summary','itinerary','booking','fairness','backup']

function initialStage(): Stage {
  const queryStage = new URLSearchParams(window.location.search).get('stage') as Stage | null
  if (queryStage && demoStages.includes(queryStage)) return queryStage
  const savedStage = localStorage.getItem('moa-v11-stage') as Stage | null
  return savedStage && demoStages.includes(savedStage) ? savedStage : 'landing'
}

function initialResultTab(): ResultTab {
  const queryTab = new URLSearchParams(window.location.search).get('tab') as ResultTab | null
  return queryTab && resultTabs.includes(queryTab) ? queryTab : 'summary'
}

const stageNav: Record<Stage, string> = {
  landing: '홈', destinations: '여행지', create: '방 만들기', invite: '친구 초대', lobby: '여행 방', hard: '설문', sliders: '설문', cards: '설문', free: '설문',
  'persona-loading': '내 대리인', persona: '내 대리인', submitted: '준비 상태', running: 'AI 회의', complete: '회의 완료', result: '최종 계획', replay: '회의 다시보기',
}

function AppV11() {
  const [stage, setStage] = useState<Stage>(initialStage)
  const [selected, setSelected] = useState<DestinationPack>(destinationPacks.find((d) => d.id === 'osaka')!)
  const [cardIndex, setCardIndex] = useState(0)
  const [scores, setScores] = useState(() => osakaPreferences.map((p) => p.defaultScore))
  const [tab, setTab] = useState<ResultTab>(initialResultTab)
  const [reason, setReason] = useState<string | null>(null)
  const [rerun, setRerun] = useState<string | null>(null)
  const [toast, setToast] = useState('')

  useEffect(() => localStorage.setItem('moa-v11-stage', stage), [stage])
  useEffect(() => { if (!toast) return; const t = window.setTimeout(() => setToast(''), 2200); return () => window.clearTimeout(t) }, [toast])
  const go = (next: Stage) => { setStage(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <div className="v11-app">
    {stage !== 'landing' && <Header stage={stage} home={() => go('landing')} room={() => go('lobby')} />}
    <AnimatePresence mode="wait">
      <motion.main key={stage} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .25 }}>
        {stage === 'landing' && <Landing create={() => go('destinations')} join={() => go('lobby')} />}
        {stage === 'destinations' && <DestinationPicker selected={selected} select={setSelected} next={() => go('create')} />}
        {stage === 'create' && <CreateRoom destination={selected} back={() => go('destinations')} next={() => go('invite')} />}
        {stage === 'invite' && <InviteSuccess next={() => go('lobby')} copy={() => setToast('초대 링크를 복사했어요')} share={() => setToast('카카오톡 공유 화면을 열었어요')} />}
        {stage === 'lobby' && <Lobby start={() => go('hard')} copy={() => setToast('초대 링크를 복사했어요')} />}
        {stage === 'hard' && <HardSurvey next={() => go('sliders')} />}
        {stage === 'sliders' && <SliderSurvey next={() => go('cards')} />}
        {stage === 'cards' && <CardSurvey index={cardIndex} scores={scores} setScore={(score) => { setScores((old) => old.map((v, i) => i === cardIndex ? score : v)); if (cardIndex < 19) setCardIndex((i) => i + 1) }} back={() => setCardIndex((i) => Math.max(0, i - 1))} next={() => go('free')} />}
        {stage === 'free' && <FreeSurvey next={() => go('persona-loading')} />}
        {stage === 'persona-loading' && <PersonaLoading next={() => go('persona')} />}
        {stage === 'persona' && <Persona confirm={() => go('submitted')} edit={() => go('hard')} />}
        {stage === 'submitted' && <Submitted next={() => go('running')} room={() => go('lobby')} />}
        {stage === 'running' && <MeetingRunning next={() => go('complete')} />}
        {stage === 'complete' && <MeetingComplete result={() => go('result')} replay={() => go('replay')} />}
        {stage === 'result' && <FinalResult tab={tab} setTab={setTab} openReason={setReason} replay={() => go('replay')} rerun={setRerun} />}
        {stage === 'replay' && <MeetingReplay back={() => go('result')} />}
      </motion.main>
    </AnimatePresence>
    <AnimatePresence>{reason && <DecisionDrawer kind={reason} close={() => setReason(null)} />}</AnimatePresence>
    <AnimatePresence>{rerun && <RerunModal category={rerun} close={() => setRerun(null)} submit={() => { setRerun(null); setToast(`${rerun} 재논의를 요청했어요`) }} />}</AnimatePresence>
    <AnimatePresence>{toast && <motion.div className="v11-toast" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}><CheckCircle weight="fill" />{toast}</motion.div>}</AnimatePresence>
  </div>
}

function Logo() { return <div className="v11-logo"><span><img src="/assets/moa-mascot.png" alt="모아" /></span><b>모아</b></div> }

function Header({ stage, home, room }: { stage: Stage; home: () => void; room: () => void }) {
  return <header className="v11-header"><button onClick={home} aria-label="모아 홈"><Logo /></button><div className="v11-breadcrumb"><span>오사카 3박 4일</span><CaretRight /><strong>{stageNav[stage]}</strong></div><div className="v11-header-actions"><button onClick={room}><UsersThree /> 여행 방</button><span className="v11-avatar">펠</span></div></header>
}

function Moa({ state = 'hello', compact = false }: { state?: string; compact?: boolean }) {
  return <div className={`v11-moa ${compact ? 'compact' : ''}`}><div className="v11-moa-halo" /><img src="/assets/moa-mascot.png" alt={`${state} 상태의 모아 캐릭터`} /></div>
}

function Landing({ create, join }: { create: () => void; join: () => void }) {
  const steps = [['01', '취향을 알려주세요', '약 7분이면 충분해요.', Clock], ['02', '대리인에게 맡겨두세요', '각자의 AI가 대신 회의해요.', Hourglass], ['03', '결과만 확인하세요', '일정과 결정 이유까지 한눈에.', ShieldCheck]] as const
  return <section className="v11-landing"><nav><Logo /><div><button className="v11-link" onClick={join}>초대받은 방 참여</button><button className="v11-button mini" onClick={create}>여행 방 만들기 <ArrowRight /></button></div></nav><div className="v11-hero"><div className="v11-hero-copy"><span className="v11-kicker"><Sparkle weight="fill" /> 7분이면 내 역할은 끝</span><h1>여행 계획 때문에<br />단톡방에서 <em>싸우지 마세요.</em></h1><p>각자 취향만 알려주면, AI 대리인들이 대신 회의하고<br className="desktop" /> 모두가 납득할 여행 계획을 만들어드려요.</p><div className="v11-actions"><button className="v11-button big" onClick={create}>여행 방 만들기 <ArrowRight /></button><button className="v11-button ghost big" onClick={join}>초대받은 방 참여하기</button></div></div><div className="v11-hero-art"><div className="v11-room-card"><small>TRIP ROOM</small><strong>오사카 3박 4일</strong><span>6명의 대리인이 회의할 예정이에요</span><div>{roomMembers.map((m) => <i key={m.name} style={{ background: m.color }}>{m.initial}</i>)}</div></div><Moa /><div className="v11-speech"><strong>취향만 알려주세요.</strong><span>회의는 모아와 대리인들에게 맡겨두세요.</span></div></div></div><div className="v11-benefits">{steps.map(([number, top, bottom, Icon], index) => <div key={number}><b>{number}</b><span><Icon weight="duotone" /></span><p><strong>{top}</strong><small>{bottom}</small></p>{index < 2 && <ArrowRight className="v11-step-arrow" />}</div>)}</div></section>
}

function DestinationPicker({ selected, select, next }: { selected: DestinationPack; select: (d: DestinationPack) => void; next: () => void }) {
  return <Page><div className="v11-page-head"><span className="v11-kicker">DESTINATION FIRST</span><h1>어디로 떠나시나요?</h1><p>여행지를 먼저 정하면, 그곳에 맞는 설문과 후보를 준비해드려요.</p></div>{(['국내', '일본'] as const).map((country) => <section className="v11-destination-group" key={country}><div><h2>{country}</h2><span>{country === '국내' ? '가볍게 떠나는 우리나라 여행' : '가깝고도 새로운 취향 여행'}</span></div><div className="v11-destination-grid">{destinationPacks.filter((d) => d.country === country).map((d) => <button key={d.id} className={`v11-destination-card ${selected.id === d.id ? 'selected' : ''}`} onClick={() => select(d)}><img src={d.image} alt={d.name} /><span className="v11-photo-shade" /><div><strong>{d.name}</strong><p>{d.tags.join(' · ')}</p></div>{selected.id === d.id && <i><Check weight="bold" /></i>}</button>)}</div></section>)}<div className="v11-request"><div><MapPin /><p><strong>찾는 곳이 없나요?</strong><span>새로운 여행지 팩을 요청해 주세요.</span></p></div><button>여행지 요청하기 <ArrowRight /></button></div><StickyAction note={`${selected.name} 여행으로 시작할게요`} button="다음" onClick={next} /></Page>
}

function CreateRoom({ destination, back, next }: { destination: DestinationPack; back: () => void; next: () => void }) {
  return <Page narrow><button className="v11-back" onClick={back}><ArrowLeft /> 여행지 다시 고르기</button><div className="v11-create-grid"><div className="v11-create-visual"><img src={destination.image} alt={destination.name} /><span className="v11-photo-shade" /><div><small>선택한 여행지</small><h2>{destination.name}</h2><p>{destination.tags.join(' · ')}</p></div></div><div className="v11-form-card"><span className="v11-kicker">TRIP ROOM</span><h1>{destination.name} 여행 만들기</h1><p>방을 만든 뒤에는 여행지를 바꿀 수 없어요.</p><label>여행 이름<input defaultValue="오사카 3박 4일" /></label><div className="v11-form-row"><label>시작일<div><CalendarBlank /><input defaultValue="2026.10.15" /></div></label><label>종료일<div><CalendarBlank /><input defaultValue="2026.10.18" /></div></label></div><div className="v11-form-row"><label>인원<div><UsersThree /><input defaultValue="6명" /></div></label><label>1인 예산 범위<div><Coins /><input defaultValue="70–90만원" /></div></label></div><label>취향 입력 마감일<div><Clock /><input defaultValue="2026.09.20 23:59" /></div></label><button className="v11-button full big" onClick={next}>여행 방 만들기 <ArrowRight /></button></div></div></Page>
}

function InviteSuccess({ next, copy, share }: { next: () => void; copy: () => void; share: () => void }) {
  return <Page narrow><section className="v11-invite-success"><div className="v11-invite-art"><Moa /><span><Check weight="bold" /></span></div><span className="v11-kicker">ROOM IS READY</span><h1>여행 방이 만들어졌어요</h1><p>친구들에게 공유하고 각자 취향만 입력하면 돼요.</p><div className="v11-invite-code"><span>초대 링크</span><strong>moa.travel/join/OSK-2410</strong><button onClick={copy} aria-label="초대 링크 복사"><Copy /></button></div><div className="v11-invite-actions"><button className="v11-button ghost big" onClick={copy}><Copy /> 링크 복사</button><button className="v11-kakao big" onClick={share}><ShareNetwork /> 카카오톡으로 공유</button></div><button className="v11-link" onClick={next}>여행 방으로 이동 <ArrowRight /></button></section></Page>
}

function Lobby({ start, copy }: { start: () => void; copy: () => void }) {
  const statusClass = (s: string) => s === '완료' ? 'done' : s === '작성 중' ? 'doing' : s === '확인 필요' ? 'confirm' : 'idle'
  return <Page><RoomHeading status="취향 받는 중" /><div className="v11-room-banner"><div><span className="v11-kicker light">INVITE YOUR CREW</span><h2>각자 편할 때 취향을 입력해요</h2><p>응답은 서로에게 보이지 않고, 전원이 준비되면 회의가 자동으로 시작돼요.</p><button onClick={copy}><Link /> 초대 링크 복사</button></div><div className="v11-deadline"><Clock /><p><small>취향 입력 마감</small><strong>9월 20일 23:59</strong></p></div></div><div className="v11-room-section-head"><div><h2>멤버 준비 상태</h2><p>함께 접속할 필요 없이 각자 대리인만 준비하면 돼요.</p></div><strong>3 / 6명 준비 완료</strong></div><div className="v11-member-grid">{roomMembers.map((m, index) => <article key={m.name}><span className="v11-member-avatar" style={{ color: m.color, background: m.pale }}>{m.initial}</span><div><strong>{m.name}{index === 0 && <i>나</i>}</strong><small>{m.status === '완료' ? '대리인 준비 완료' : m.status === '작성 중' ? '취향 입력 중 · 65%' : m.status === '확인 필요' ? '페르소나 확인 필요' : '아직 시작 전'}</small></div><em className={statusClass(m.status)}>{m.status}</em></article>)}</div><div className="v11-callout"><span><Sparkle weight="fill" /></span><div><strong>펠리시아님의 대리인을 준비해 볼까요?</strong><p>약 7분이면 끝나요. 제출한 뒤에는 앱을 나가도 괜찮아요.</p></div><button className="v11-button" onClick={start}>내 취향 입력하기 <ArrowRight /></button></div></Page>
}

function SurveyShell({ step, time, title, copy, children, next, nextLabel = '다음' }: { step: number; time: string; title: string; copy: string; children: React.ReactNode; next: () => void; nextLabel?: string }) {
  return <Page narrow><SurveyProgress step={step} time={time} /><div className="v11-survey-title"><span className="v11-kicker">PART {step} OF 4</span><h1>{title}</h1><p>{copy}</p></div>{children}<StickyAction note={step < 4 ? `약 ${time} 남았어요` : '이제 대리인을 만들 차례예요'} button={nextLabel} onClick={next} /></Page>
}

function SurveyProgress({ step, time }: { step: number; time: string }) { return <div className="v11-survey-progress"><div>{[1,2,3,4].map((n) => <span className={n <= step ? 'active' : ''} key={n} />)}</div><p><strong>{step} / 4</strong><small>약 {time} 남았어요</small></p></div> }

function HardSurvey({ next }: { next: () => void }) {
  const [diet, setDiet] = useState('없음'); const [nope, setNope] = useState(['새벽 비행', '도미토리']); const togg = (v: string) => setNope((old) => old.includes(v) ? old.filter((x) => x !== v) : [...old, v])
  return <SurveyShell step={1} time="6분" title="이건 꼭 지켜주세요" copy="여기에 입력한 조건은 AI 대리인이 절대 양보하지 않아요." next={next}><div className="v11-hard-grid"><SurveyCard icon={Coins} title="예산"><label className="v11-field">1인 총예산 상한<div className="v11-money"><b>₩</b><input defaultValue="900,000" /><span>원</span></div></label><label className="v11-switch"><input type="checkbox" defaultChecked /><span /> 항공 포함</label></SurveyCard><SurveyCard icon={ForkKnife} title="식이 조건"><ChipGroup items={['없음','비건','베지테리언','할랄','코셔','알레르기']} selected={[diet]} select={(v) => setDiet(v)} /></SurveyCard><SurveyCard icon={ShieldCheck} title="신념 · 생활 조건"><ChipGroup items={['기도 시간 필요','음주 일정 제외','동물 체험 제외']} selected={[]} select={() => {}} plus /></SurveyCard><SurveyCard icon={SuitcaseRolling} title="체력 · 이동"><label className="v11-field">하루 가능한 도보 거리<input type="range" min="1" max="15" defaultValue="6" /><div className="v11-range-label"><span>1km</span><strong>6km</strong><span>15km</span></div></label><ChipGroup items={['계단·경사 어려움','휠체어','유아차']} selected={[]} select={() => {}} /></SurveyCard></div><SurveyCard icon={LockKey} title="절대 불가" full><ChipGroup items={['새벽 비행','도미토리','남녀 혼숙','날것','놀이기구','장시간 버스','흡연실']} selected={nope} select={togg} plus /></SurveyCard><div className="v11-warning"><Warning weight="fill" /><p><strong>마지막으로 한 번 더 확인해 주세요.</strong><span>여기에 적지 않은 절대 조건은 회의에서 반영되지 않을 수 있어요.</span></p></div></SurveyShell>
}

function SliderSurvey({ next }: { next: () => void }) {
  const [values, setValues] = useState<number[]>(preferenceSliders.map((p) => p[3]))
  return <SurveyShell step={2} time="4분" title="어떤 여행을 좋아하세요?" copy="가까운 쪽으로 톡톡 옮겨주세요. 오래 고민하지 않아도 괜찮아요." next={next}><div className="v11-slider-grid">{preferenceSliders.map(([title,left,right], i) => <article className="v11-slider" key={title}><div><strong>{title}</strong><span>{values[i]} / 7</span></div><input type="range" min="1" max="7" value={values[i]} onChange={(e) => setValues((old) => old.map((v,n) => n === i ? Number(e.target.value) : v))} /><footer><span>{left}</span><span>{right}</span></footer></article>)}</div><div className="v11-tip"><Moa compact /><p><strong>모아의 TIP</strong><span>가운데를 골라도 좋아요. 대리인은 애매함까지 솔직하게 전달해요.</span></p></div></SurveyShell>
}

function CardSurvey({ index, scores, setScore, back, next }: { index: number; scores: number[]; setScore: (n: number) => void; back: () => void; next: () => void }) {
  const item = osakaPreferences[index]
  const label = (n: number) => n >= 9 ? '꼭 하고 싶어요' : n >= 7 ? '좋아요' : n >= 5 ? '있어도 좋아요' : n >= 3 ? '별로 관심 없어요' : '피하고 싶어요'
  return <SurveyShell step={3} time="2분" title="오사카에서 뭘 하고 싶나요?" copy="좋고 싫음을 빠르게 점수로 알려주세요. 스와이프가 아닌 1–10 선호도예요." next={next} nextLabel={index === 19 ? '마지막 질문으로' : '평가 완료'}><div className="v11-card-counter"><strong>{index + 1}</strong> / 20<div><i style={{ width: `${(index + 1) * 5}%` }} /></div></div><motion.article key={index} className="v11-score-card" initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }}><img src={item.image} alt={item.name} /><span className="v11-photo-shade" /><div><span>OSAKA PICK {String(index + 1).padStart(2,'0')}</span><h2>{item.name}</h2><p>{item.context}</p></div></motion.article><div className="v11-score-selector"><div><span>관심 없어요</span><strong><b>{scores[index]}</b> — {label(scores[index])}</strong><span>꼭 할래요</span></div><div>{[1,2,3,4,5,6,7,8,9,10].map((n) => <button className={scores[index] === n ? 'active' : ''} key={n} onClick={() => setScore(n)}>{n}</button>)}</div></div><div className="v11-card-nav"><button onClick={back} disabled={index === 0}><ArrowLeft /> 이전 카드</button><p>숫자를 고르면 다음 카드로 바로 넘어가요</p></div></SurveyShell>
}

function FreeSurvey({ next }: { next: () => void }) { return <SurveyShell step={4} time="1분" title="마지막으로, 한마디만 더" copy="대리인이 꼭 기억해야 할 내용 두 가지만 자유롭게 알려주세요." next={next} nextLabel="내 AI 대리인 만들기"><div className="v11-free-grid"><label><span><TrendUp />이번 여행에서 이것만은 꼭 하고 싶어요.</span><textarea maxLength={100} defaultValue="여행 중 하루는 온천에서 느긋하게 쉬고, 로컬 이자카야도 꼭 가고 싶어요." /><small>46 / 100</small></label><label><span><TrendDown />이것만은 정말 피하고 싶어요.</span><textarea maxLength={100} defaultValue="새벽 비행과 너무 빡빡한 일정은 피하고 싶어요. 숙소는 한 곳에서 지내고 싶습니다." /><small>45 / 100</small></label></div></SurveyShell> }

function PersonaLoading({ next }: { next: () => void }) { useEffect(() => { const t = window.setTimeout(next, 2600); return () => clearTimeout(t) }, [next]); return <section className="v11-loading"><Moa /><span className="v11-kicker">BUILDING MY AGENT</span><h1>당신의 AI 대리인을<br />만들고 있어요.</h1><p>답변에서 절대 조건, 중요한 취향, 양보 가능한 부분을 정리하는 중이에요.</p><div>{['절대 조건 확인','선호 우선순위 정리','협상 스타일 생성'].map((x,i) => <span style={{ animationDelay: `${i*.35}s` }} key={x}><SpinnerGap />{x}</span>)}</div></section> }

function Persona({ confirm, edit }: { confirm: () => void; edit: () => void }) {
  return <Page narrow><div className="v11-persona-head"><span className="v11-kicker">MY AGENT</span><h1>내 여행 대리인이 준비됐어요</h1><p>회의에 보내기 전에, 나를 제대로 이해했는지 확인해 주세요.</p></div><div className="v11-persona-card"><div className="v11-persona-side"><div className="v11-agent-avatar"><span>펠</span><i><Sparkle weight="fill" /></i></div><small>펠리시아의 AI 대리인</small><h2>“맛집은 포기 못하는<br />느긋한 탐험가”</h2><p>숙소보다 음식과 경험에 투자하고, 모두가 지치지 않는 절충안을 찾아요.</p><span className="v11-agent-style">협상 스타일 · 조정형</span></div><div className="v11-persona-details"><PersonaBlock icon={Coins} title="예산"><strong>₩900,000</strong><span>항공 포함 · 상한 엄격</span></PersonaBlock><PersonaBlock icon={Clock} title="여행 스타일"><strong>느긋한 편</strong><span>하루 2–3곳 정도</span></PersonaBlock><PersonaBlock icon={LockKey} title="절대 조건"><div className="v11-mini-chips"><i>새벽 비행 불가</i><i>도미토리 불가</i><i>갑각류 알레르기</i></div></PersonaBlock><PersonaBlock icon={TrendUp} title="가장 기대돼요"><div className="v11-rank-list"><span>스파월드 <b>9</b></span><span>도톤보리 <b>9</b></span><span>구로몬 시장 <b>8</b></span></div></PersonaBlock><PersonaBlock icon={TrendDown} title="관심이 적어요"><div className="v11-rank-list low"><span>신사이바시 <b>2</b></span><span>아쿠아리움 <b>1</b></span></div></PersonaBlock><PersonaBlock icon={Gavel} title="협상 방식"><strong>조정형</strong><span>부딪힐 때 서로 납득할 절충안을 찾아요.</span></PersonaBlock></div></div><div className="v11-confirm-gate"><ShieldCheck weight="duotone" /><div><strong>이 대리인이 펠리시아님을 대신해요.</strong><span>여행 회의가 시작되면 이 내용을 기준으로 의견을 내고 협상해요. 시작 이후에는 수정할 수 없어요.</span></div></div><div className="v11-persona-actions"><button className="v11-button ghost big" onClick={edit}>수정할래요</button><button className="v11-button big" onClick={confirm}>이대로 보낼게요 <ArrowRight /></button></div></Page>
}

function Submitted({ next, room }: { next: () => void; room: () => void }) { return <section className="v11-submitted"><div className="v11-check-orbit"><Moa /><span><Check weight="bold" /></span></div><span className="v11-kicker">AGENT SUBMITTED</span><h1>이제 맡겨두세요.</h1><p>모든 멤버의 준비가 끝나면 AI 대리인들이 자동으로 회의를 시작해요.</p><div className="v11-readiness"><div><strong>4 / 6명</strong><span>준비 완료</span></div><div>{roomMembers.map((m,i) => <span key={m.name} style={{ background: i < 4 ? m.color : '#d8d2ca' }}>{i < 4 ? <Check /> : m.initial}</span>)}</div></div><div className="v11-leave-note"><Bell weight="duotone" /><p><strong>지금 앱을 나가셔도 괜찮아요.</strong><span>계획이 완성되면 알려드릴게요.</span></p></div><div className="v11-actions"><button className="v11-button ghost" onClick={room}>준비 상태 보기</button><button className="v11-button" onClick={next}>회의 시작 상태 미리보기 <ArrowRight /></button></div></section> }

function MeetingRunning({ next }: { next: () => void }) {
  return <Page narrow><div className="v11-running-head"><div><span className="v11-kicker">BACKGROUND MEETING</span><h1>대리인들이 회의 중이에요</h1><p>앱을 켜두지 않아도 회의는 계속됩니다.</p></div><div className="v11-running-moa"><Moa compact /><span><SpinnerGap />조율 중</span></div></div><div className="v11-rounds">{meetingRounds.map((r,i) => <article className={r.state === '논의 중' ? 'active' : ''} key={r.code}><span>{r.code}</span><div><strong>{r.name}</strong><small>{i === 0 ? '여행 페이스 · 우선순위' : i === 1 ? '공항 · 패스 · 택시' : i === 2 ? '난바 후보 4곳 검토' : '앞선 결정 후 검토 예정'}</small></div><em className={r.state === '완료' ? 'done' : r.state === '논의 중' ? 'doing' : ''}>{r.state === '완료' ? <CheckCircle weight="fill" /> : r.state === '논의 중' ? <SpinnerGap /> : <Clock />}{r.state}</em></article>)}</div><div className="v11-async-note"><Hourglass weight="duotone" /><div><strong>약 5–20분 정도 걸릴 수 있어요.</strong><p>기다리지 않으셔도 됩니다. 완료되면 바로 알려드릴게요.</p></div><label><input type="checkbox" defaultChecked /><span /> 회의가 끝나면 알림 받기</label></div><div className="v11-actions center"><button className="v11-button ghost">나중에 확인하기</button><button className="v11-button" onClick={next}>완료 상태 미리보기 <ArrowRight /></button></div></Page>
}

function MeetingComplete({ result, replay }: { result: () => void; replay: () => void }) { return <section className="v11-complete"><div className="v11-confetti">{Array.from({length: 14}).map((_,i) => <i key={i} style={{ '--i': i } as React.CSSProperties} />)}</div><div className="v11-complete-art"><Moa /><span><Gavel weight="fill" /></span></div><span className="v11-kicker">MEETING COMPLETE</span><h1>오사카 여행 회의가<br />끝났어요!</h1><p>7개의 안건을 논의하고 모두의 조건을 반영한 여행 계획을 만들었어요.</p><div className="v11-complete-stats"><span><strong>7</strong>논의 라운드</span><span><strong>42</strong>검토한 후보</span><span><strong>7.7</strong>평균 만족도</span></div><div className="v11-actions"><button className="v11-button ghost big" onClick={replay}>회의 과정 먼저 보기</button><button className="v11-button big" onClick={result}>결과 확인하기 <ArrowRight /></button></div></section> }

function FinalResult({ tab, setTab, openReason, replay, rerun }: { tab: ResultTab; setTab: (t: ResultTab) => void; openReason: (s: string) => void; replay: () => void; rerun: (s: string) => void }) {
  const tabs: [ResultTab,string][] = [['summary','한눈에 보기'],['itinerary','상세 일정'],['booking','예약 · 예산'],['fairness','공평함'],['backup','Plan B']]
  return <Page><RoomHeading status="회의 완료" completed /><div className="v11-result-meta"><span><CheckCircle weight="fill" /> 회의 완료</span><p>7라운드 · 재심 1회 · 42개 후보 검토</p><button onClick={replay}><Play weight="fill" /> AI 회의 다시보기</button></div><nav className="v11-result-tabs">{tabs.map(([key,label]) => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key)} key={key}>{label}</button>)}</nav>{tab === 'summary' && <SummaryTab openReason={openReason} setTab={setTab} />}{tab === 'itinerary' && <ItineraryTab openReason={openReason} />}{tab === 'booking' && <BookingTab />}{tab === 'fairness' && <FairnessTab />}{tab === 'backup' && <BackupTab />}<RerunSection open={rerun} /></Page>
}

function SummaryTab({ openReason, setTab }: { openReason: (s: string) => void; setTab: (t: ResultTab) => void }) {
  const snapshot = [{ value: '3박 4일', label: '여행 기간', Icon: CalendarBlank }, { value: '₩780,000', label: '1인 예상', Icon: Coins }, { value: '난바', label: '핵심 지역', Icon: MapPin }, { value: '4건', label: '예약 필요', Icon: Ticket }, { value: '7.7', label: '평균 만족도', Icon: ChartDonut }]
  return <div className="v11-result-content"><section className="v11-satisfaction"><div className="v11-summary-title"><div><span className="v11-kicker">SATISFACTION FIRST</span><h2>그래서, 모두의 의견이<br />얼마나 반영됐을까요?</h2></div><div className="v11-main-score"><strong>7.7</strong><span>/ 10 평균 만족도</span><em><Check /> 전원 6점 이상</em></div></div><div className="v11-member-scores">{roomMembers.map((m,i) => <article key={m.name}><div><span style={{ background: m.color }}>{m.initial}</span><strong>{m.name}</strong>{i === 0 && <i>나</i>}</div><b>{m.score.toFixed(1)}</b><div><span style={{ width: `${m.score*10}%`, background: m.color }} /></div><small>{i === 0 ? '숙소에서 조금 양보' : i === 5 ? '액티비티에서 양보' : '선호 고르게 반영'}</small></article>)}</div><div className="v11-min-score"><ShieldCheck weight="duotone" /><p><strong>최저 만족도 7.2 / 10</strong><span>평균만 높이지 않고, 누구도 크게 손해 보지 않도록 조율했어요.</span></p></div></section><section className="v11-trip-snapshot"><span className="v11-kicker">TRIP AT A GLANCE</span><h2>느긋한 페이스 · 미식 중심 · 1인 약 78만원</h2><div>{snapshot.map(({value,label,Icon}) => <article key={label}><Icon weight="duotone" /><strong>{value}</strong><span>{label}</span></article>)}</div></section><section className="v11-decision-highlight"><div><span className="v11-kicker">KEY DECISION</span><h2>숙소는 난바 H-03으로<br />3박 동안 한 곳만 이용해요.</h2><p>이동 편의와 수아의 ‘숙소 이동 불가’ 선호를 함께 반영했어요.</p><button onClick={() => openReason('숙소')}><Sparkle weight="fill" /> 왜 이렇게 결정됐나요?</button></div><div className="v11-hotel-card"><Buildings weight="duotone" /><small>SELECTED</small><strong>난바 호텔 H-03</strong><span>역 도보 7분 · 6인 투숙 · 1인 ₩210,000</span></div></section><button className="v11-next-section" onClick={() => setTab('itinerary')}>상세 일정 이어서 보기 <ArrowRight /></button></div>
}

function ItineraryTab({ openReason }: { openReason: (s: string) => void }) { const [day,setDay]=useState(0); const d=itineraryDays[day]; return <div className="v11-result-content"><div className="v11-itinerary-layout"><aside><span className="v11-kicker">FINAL PLAN</span><h2>날짜별 일정</h2><p>무리한 이동을 줄이고, 하루에 한 번은 여유 시간을 남겼어요.</p><div>{itineraryDays.map((x,i) => <button className={day===i?'active':''} onClick={() => setDay(i)} key={x.day}><span>{x.day}</span><strong>{x.title}</strong><CaretRight /></button>)}</div></aside><section className="v11-day-plan"><header><div><span>{d.day}</span><h2>{d.title}</h2></div><p><span>총 도보 <b>{d.walk}</b></span><span>총 이동 <b>{d.travel}</b></span></p></header><div>{d.items.map(([time,title,meta],i) => <article key={title}><time>{time}</time><span className="v11-time-dot"><i />{i<d.items.length-1&&<b />}</span><div><strong>{title}</strong><p>{meta}</p>{meta.includes('예약') && <em>예약 필요</em>}</div></article>)}</div><button className="v11-why" onClick={() => openReason('동선')}><Sparkle weight="fill" /> 이 동선은 왜 선택됐나요? <ArrowRight /></button></section><RouteMap day={day} /></div></div> }

function RouteMap({ day }: { day: number }) {
  const pins = [[18,72],[37,50],[56,63],[70,38],[84,57]]
  return <section className="v11-route-map"><header><div><span className="v11-kicker">ROUTE MAP</span><h2>{itineraryDays[day].day} 이동 경로</h2></div><span>지도는 일정 이해를 돕는 예시예요</span></header><div className="v11-map-canvas"><span className="v11-river river-a"/><span className="v11-river river-b"/><span className="v11-map-line"/>{pins.map(([left,top],i)=><motion.i key={`${day}-${i}`} style={{left:`${left}%`,top:`${top}%`}} initial={{scale:0}} animate={{scale:1}} transition={{delay:i*.06}}><b>{i+1}</b></motion.i>)}<strong className="v11-map-label a">난바</strong><strong className="v11-map-label b">도톤보리</strong><strong className="v11-map-label c">우메다</strong></div><footer><span><i/>선택 일정</span><b>복잡한 마커 없이 오늘의 동선만 보여줘요.</b></footer></section>
}

function BookingTab() { return <div className="v11-result-content"><div className="v11-section-heading"><span className="v11-kicker">TO BOOK</span><h2>미리 예약해야 해요</h2><p>마감이 가까운 항목부터 확인해 주세요.</p></div><div className="v11-reservations">{reservations.map(([type,name,price,status],i) => { const Icon=[AirplaneTilt,Buildings,ForkKnife,Ticket][i]; return <article key={type}><span><Icon weight="duotone" /></span><div><small>{type} · 10월 {i===0?'15일':'1일까지'}</small><strong>{name}</strong><p>{price} / 인</p></div><em className={status==='예약 완료'?'done':''}>{status}</em><button>{status==='예약 완료'?'예약 정보 보기':'예약 페이지 열기'} <ArrowRight /></button></article>})}</div><div className="v11-budget"><div><span className="v11-kicker">BUDGET</span><h2>예상 비용</h2><p>모든 멤버의 최대 예산 안에 있어요.</p><div className="v11-budget-total"><span>1인 예상 합계</span><strong>₩780,000</strong><em><Check /> 전원 예산 충족</em></div></div><div>{budget.map(([label,value],i) => <p key={label}><span>{label}</span><i><b style={{ width: `${Number(value)/3100}%`, background: ['#F2714B','#6C9E79','#D99B3D','#8B78B8','#4D8CA8'][i] }} /></i><strong>₩{Number(value).toLocaleString()}</strong></p>)}<div className="v11-common-money"><Receipt /><span><strong>그룹 공동경비 ₩1,200,000</strong><small>여행 후 1/N로 정산해요.</small></span></div></div></div></div> }

function FairnessTab() { return <div className="v11-result-content"><div className="v11-section-heading"><span className="v11-kicker">FAIRNESS, EXPLAINED</span><h2>이번 여행에서는 이렇게 맞췄어요</h2><p>의견이 채택되지 않았어도, 다른 라운드에서 우선권을 돌려받도록 조율했어요.</p></div><div className="v11-concessions">{roomMembers.map((m,i) => <article key={m.name}><header><span style={{background:m.color}}>{m.initial}</span><div><strong>{m.name}</strong><small>만족도 {m.score.toFixed(1)}</small></div></header><div><p><TrendDown />{i%2===0?'숙소 · 일부 양보':'액티비티 · 일부 양보'}</p><p><TrendUp />{i%2===0?'식사 · 우선 반영':'동선 · 우선 반영'}</p></div><footer>{i===0?'숙소에서는 조금 양보했지만, 식사와 액티비티에서는 우선순위가 더 많이 반영됐어요.':'한 가지 선호는 양보했지만 가장 중요한 절대 조건은 모두 지켜졌어요.'}</footer></article>)}</div><section className="v11-dissent"><div className="v11-section-heading"><span className="v11-kicker">MINORITY OPINIONS</span><h2>선택되진 않았지만, 기록했어요</h2></div><article><span style={{background:roomMembers[5].color}}>수</span><div><strong>수아</strong><blockquote>“숙소를 옮기지 않는 일정이 더 좋았어요.”</blockquote><p><Check /> 그래서 3일차에도 난바 숙소를 유지하고 짐 보관 서비스를 추가했어요.</p></div></article><article><span style={{background:roomMembers[3].color}}>민</span><div><strong>민재</strong><blockquote>“교토보다 유니버설 스튜디오가 더 끌렸어요.”</blockquote><p><Check /> 선택되지는 않았지만 DAY 2 저녁 자유시간을 넉넉히 확보했어요.</p></div></article></section></div> }

function BackupTab() { return <div className="v11-result-content"><div className="v11-section-heading"><span className="v11-kicker">PLAN B</span><h2>혹시 계획대로 안 된다면?</h2><p>날씨와 예약 실패까지 미리 대비했어요.</p></div><div className="v11-planb-grid"><PlanB icon={Warning} title="비 오는 날" from="오사카성 야외 일정" to="나카노시마 미술관" note="이동 시간 +8분 · 비용 +₩12,000" /><PlanB icon={ForkKnife} title="식당 예약 실패" from="이자카야 B" to="후보 2위 이자카야 C" note="도보 4분 거리 · 예산 동일" /></div><div className="v11-section-heading issue"><span className="v11-kicker">STILL TO CHECK</span><h2>아직 확인이 필요한 것</h2></div><div className="v11-issues"><article><Warning weight="fill" /><div><strong>이자카야 B</strong><p>6인 예약 가능 여부를 직접 확인해야 해요.</p></div><em>확인 필요</em></article><article><Info weight="fill" /><div><strong>가격 변동 가능</strong><p>항공과 숙소 가격은 실제 예약 시점에 달라질 수 있어요.</p></div><em>참고</em></article></div></div> }

function MeetingReplay({ back }: { back: () => void }) {
  const [round,setRound]=useState(2), [filter,setFilter]=useState('전체'), [expanded,setExpanded]=useState(false), [playing,setPlaying]=useState(true), [speed,setSpeed]=useState(1)
  const matches = (m: typeof replayMessages[number]) => filter==='전체'||filter==='내 대리인'&&m.speaker.includes('펠리시아')||filter==='다른 대리인'&&m.type==='agent'&&!m.speaker.includes('펠리시아')||filter==='심판'&&['fact','verdict'].includes(m.type)||filter==='Chief'&&m.type==='chief'
  const visible = replayMessages.filter((m) => (expanded || m.round===round) && matches(m))
  return <Page><button className="v11-back" onClick={back}><ArrowLeft /> 최종 계획으로 돌아가기</button><div className="v11-replay-head"><div><span className="v11-kicker">MEETING REPLAY</span><h1>AI 회의 다시보기</h1><p><CheckCircle weight="fill" /> 완료된 회의를 다시 보고 있어요.</p></div><div className="v11-replay-summary"><Gavel weight="duotone" /><span><strong>7개 라운드 완료</strong><small>대리인 6명 · 분야별 심판 · Chief</small></span></div></div><div className="v11-round-nav">{meetingRounds.map((r,i) => <button className={round===i&&!expanded?'active':''} onClick={() => {setRound(i);setExpanded(false)}} key={r.code}><span>{r.code}</span>{r.name}</button>)}</div><div className="v11-replay-controls"><div>{['전체','내 대리인','다른 대리인','심판','Chief'].map((x) => <button className={filter===x?'active':''} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div><div><button onClick={() => setExpanded(!expanded)}>{expanded?'현재 라운드':'전체 보기'}</button><button onClick={() => setSpeed(speed===1?2:1)}>{speed}x</button><button onClick={() => setPlaying(!playing)}>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}{playing?'일시정지':'재생'}</button></div></div><div className="v11-replay-layout"><aside><small>현재 라운드</small><strong>{expanded?'전체 회의':`${meetingRounds[round].code} ${meetingRounds[round].name}`}</strong><p>{round===2?'6인 투숙, 예산, 위치, 숙소 이동 여부를 근거로 후보 4곳을 검토했어요.':'각자의 우선순위와 절대 조건을 근거로 후보를 비교했어요.'}</p><div><span>진행 상태</span><b>판결 완료</b></div></aside><section className="v11-message-stream"><AnimatePresence>{visible.length ? visible.map((m,i) => <AgentMessage key={`${m.speaker}-${i}`} message={m} delay={playing ? i*.16/speed : 0} />) : <div className="v11-empty"><Info />선택한 필터에 해당하는 기록이 없어요.</div>}</AnimatePresence></section></div></Page>
}

function AgentMessage({ message, delay }: { message: typeof replayMessages[number]; delay: number }) {
  if (message.type === 'conflict') return <motion.article className="v11-agent-message conflict" initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} transition={{delay}}><span><Warning weight="fill" /></span><div><small>{message.speaker}</small><div className="v11-conflict-pair"><p><b>펠리시아</b>경험에 예산 우선</p><em>VS</em><p><b>서연</b>숙소 위치와 품질 우선</p></div><footer>{message.text}</footer></div></motion.article>
  const icons={agent:UsersThree,fact:ShieldCheck,verdict:Gavel,chief:Sparkle}; const Icon=icons[message.type as keyof typeof icons]
  return <motion.article className={`v11-agent-message ${message.type}`} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay}}><span><Icon weight={message.type==='verdict'||message.type==='chief'?'fill':'duotone'} /></span><div><small>{message.speaker}</small>{message.type==='fact'&&<em>FACT CHECK</em>}{message.type==='verdict'&&<em>판결</em>}{message.type==='chief'&&<em>CHIEF REVIEW</em>}<p>{message.type==='agent'?`“${message.text}”`:message.text}</p>{message.type==='fact'&&<div className="v11-evidence"><span><Check /> 실제 후보 확인</span><span><Check /> 절대 조건 확인</span><span><Check /> 예산 확인</span></div>}{message.type==='verdict'&&<strong className="v11-replay-outcome"><CheckCircle weight="fill" /> 판결 확정</strong>}</div></motion.article>
}

function DecisionDrawer({ kind, close }: { kind: string; close: () => void }) { return <motion.div className="v11-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={close}><motion.aside className="v11-drawer" initial={{x:480}} animate={{x:0}} exit={{x:480}} onMouseDown={(e)=>e.stopPropagation()}><header><div><span className="v11-kicker">DECISION REASON</span><h2>{kind} — 왜 이렇게 결정됐나요?</h2></div><button onClick={close}><X /></button></header><div className="v11-verdict"><Gavel weight="duotone" /><div><small>최종 선택</small><strong>{kind==='숙소'?'난바 호텔 H-03':kind==='동선'?'난바 중심 방사형 동선':'선택안'}</strong></div></div><section><h3>선택 이유</h3>{['6명 모두 이용 가능한 후보예요.','모든 멤버의 예산 범위 안에 있어요.','주요 일정과 이동거리가 가장 짧아요.','도미토리 불가와 숙소 이동 불가 조건을 충족해요.'].map((x)=><p key={x}><Check />{x}</p>)}</section><section><h3>누구의 의견이 반영됐나요?</h3><div className="v11-reflection">{roomMembers.slice(0,4).map((m,i)=><span key={m.name} style={{background:m.pale,color:m.color}}>{m.name} {i<3?'선호':'양보'}</span>)}</div></section><div className="v11-fact-source"><ShieldCheck /><p><strong>팩트체크 완료</strong><span>6인 투숙 가능 여부와 총 숙박비를 후보 데이터에서 확인했어요.</span></p></div><button className="v11-button full" onClick={close}>이해했어요</button></motion.aside></motion.div> }

function RerunSection({ open }: { open: (s:string) => void }) { return <section className="v11-rerun"><div><span className="v11-kicker">ONE CATEGORY AT A TIME</span><h2>마음에 안 드는 부분이 있나요?</h2><p>전체 계획을 처음부터 만들지 않고, 선택한 카테고리와 영향을 받는 결정만 다시 논의해요.</p><strong>무료 재논의 2회 남음</strong></div><div>{['숙소','식사','액티비티','교통'].map((x)=><button key={x} onClick={()=>open(x)}>{x} 다시 논의 <ArrowRight /></button>)}</div></section> }

function RerunModal({ category, close, submit }: { category:string; close:()=>void; submit:()=>void }) { return <motion.div className="v11-modal-bg" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={close}><motion.div className="v11-rerun-modal" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} onMouseDown={(e)=>e.stopPropagation()}><button className="v11-modal-close" onClick={close}><X /></button><span className="v11-kicker">REOPEN {category.toUpperCase()}</span><h2>{category}, 어떤 부분이 아쉬웠나요?</h2><p>이 내용은 모든 대리인과 {category} 심판에게 전달돼요.</p><textarea placeholder="예: 숙소가 역에서 조금 더 가까우면 좋겠어요." /><div className="v11-rerun-impact"><Info /><span><strong>다시 검토할 범위</strong>{category} 후보와 관련된 예산·동선만 업데이트합니다.</span></div><button className="v11-button full big" onClick={submit}>이 카테고리 다시 논의하기 <MagicWand /></button></motion.div></motion.div> }

function RoomHeading({ status, completed=false }: { status:string; completed?:boolean }) { return <div className="v11-room-heading"><div><span className="v11-kicker">OSAKA · TRIP ROOM</span><h1>오사카 3박 4일</h1><p><CalendarBlank /> 2026.10.15 – 10.18 <span>·</span><UsersThree /> 6명</p></div><em className={completed?'completed':''}>{completed?<CheckCircle weight="fill"/>:<span/>}{status}</em></div> }
function Page({ children, narrow=false }: { children:React.ReactNode; narrow?:boolean }) { return <div className={`v11-page ${narrow?'narrow':''}`}>{children}</div> }
function StickyAction({ note, button, onClick }: { note:string; button:string; onClick:()=>void }) { return <div className="v11-sticky"><p><CheckCircle weight="fill" />{note}</p><button className="v11-button" onClick={onClick}>{button}<ArrowRight /></button></div> }
function SurveyCard({ icon:Icon,title,children,full=false }: { icon:typeof Coins; title:string; children:React.ReactNode; full?:boolean }) { return <section className={`v11-survey-card ${full?'full':''}`}><header><span><Icon weight="duotone" /></span><h2>{title}</h2></header>{children}</section> }
function ChipGroup({ items,selected,select,plus=false }: { items:string[]; selected:string[]; select:(x:string)=>void; plus?:boolean }) { return <div className="v11-chip-group">{items.map((x)=><button className={selected.includes(x)?'active':''} onClick={()=>select(x)} key={x}>{selected.includes(x)&&<Check/>}{x}</button>)}{plus&&<button><Plus/>직접 입력</button>}</div> }
function PersonaBlock({ icon:Icon,title,children }: { icon:typeof Coins; title:string; children:React.ReactNode }) { return <section className="v11-persona-block"><header><Icon weight="duotone" /><span>{title}</span></header><div>{children}</div></section> }
function PlanB({ icon:Icon,title,from,to,note }: { icon:typeof Warning; title:string; from:string; to:string; note:string }) { return <article className="v11-planb"><header><span><Icon weight="duotone" /></span><div><small>IF · {title}</small><strong>{title}</strong></div></header><div><p><small>ORIGINAL</small><strong>{from}</strong></p><ArrowRight/><p><small>PLAN B</small><strong>{to}</strong></p></div><footer>{note}</footer></article> }

export default AppV11
